### ISSUE TITLE
Table images should not resize based on browser width

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej.github.io#100]
Check out e.g. https://imagej.github.io/about/. The logos gets smaller as you reduce the browser width, down to the point of disappearing. They should rather be a fixed size. Figure out what in the CSS is causing this to happen. Noticed by @imagejan.

**Comment by hinerm** [comment]
Did the logos get taken off this page?

**Comment by ctrueden** [comment]
They're there! Just very small!
![tiny-logos](https://user-images.githubusercontent.com/556626/119057779-b94b0f80-b992-11eb-988e-ae45f722a627.png)

**Comment by hinerm** [comment]
>They're there! Just very small!

lol I thought those were bullet points...

**Comment by hinerm** [comment]
I decided to pull off the `max-width:100%` css from all images since it seems way too aggressive.

@ctrueden @elevans do you know of any location where this css was actually needed?

**Comment by ctrueden** [comment]
> it seems way too aggressive.

I agree.

> do you know of any location where this css was actually needed? 

The main upside was to avoid very large images with no explicitly declared size going way outside the content pane. Of course we could crop it with `overflow: hidden` or whatnot, but I don't think it would actually downsample the image in that case? So I tried to reintroduce the rule, but in a controlled way, and with mitigation to avoid the biggest problem of images in a table being treated badly. See 97956016b252295136b0cfd2aad748ad3787f601.
