### ISSUE TITLE
Create (or remove links to) missing editing pages

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej.github.io#113]
The following pages are linked to in the menu but don't exist yet:

* `/help/editing/conferences`
* `/help/editing/logo`
* ` /help/editing/sideboxes`

We need to create these pages or remove the links.

**Comment by hinerm** [comment]
@ctrueden if you have a chance could you give a brief summary of the purpose of each page?

**Comment by ctrueden** [comment]
@hinerm Thanks, I cleaned it up. I forgot that the main menu linked these pages, but so does the nav-bar now. They were simply out of sync. Should we remove the secondary links from the main menu, in favor of only the nav-bar? What do you think?

**Comment by hinerm** [comment]
>Should we remove the secondary links from the main menu, in favor of only the nav-bar? What do you think?

@ctrueden is there supposed to be a persistent `nav-bar` somewhere? I'm not seeing anything that would replace the main menu.. I think things are fine the way they are now though. I like the menu
