### ISSUE TITLE
Icons page is missing its page content menu

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej.github.io#125]
https://imagej.github.io/editing/icons

Where did it go?

![image](https://user-images.githubusercontent.com/1123809/120013273-29b2eb80-bfa6-11eb-845b-1acf9fbce3fa.png)

**Comment by ctrueden** [comment]
The TOC was set to only appear when three or more headings exist. I guess the thinking was that with only two headings, the TOC looks kind of bare? But it's still useful when there are two, so I changed it.

**Comment by hinerm** [comment]
@ctrueden did you change it but not push? I don't see anything still

**Comment by hinerm** [comment]
The "Page Contents" window flashes when I load the page and then disappears

**Comment by hinerm** [comment]
ah I see.. now the page only has one heading

**Comment by ctrueden** [comment]
Should we just never hide the TOC? It would be a bit weird to have an empty one with zero headings, though.

**Comment by hinerm** [comment]
>Should we just never hide the TOC? It would be a bit weird to have an empty one with zero headings, though.

Agreed. I think it's fine to show it if there's at least one H2. But I don't feel strongly
