### ISSUE TITLE
Improve the website's search functionality

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej.github.io#13]
Right now the search functionality is purely client-side, which I personally love. However, @turekg has developed a more badass server-side search as part of an effort to better index our community's public conversations on Gitter, which could also be utilized for imagej.net content and more. The goal is to fully replace the rather cheesy https://search.imagej.net site with a unified and integrated search from imagej.net itself.

This is not an immediate goal before we cut over from MediaWiki, but is a strong "would be awesome" goal we want to pursue soon, depending on how the quality of the initial client-side search ends up being once the existing content has been migrated (see #11).

**Comment by ctrueden** [comment]
I want to use [typesense](https://typesense.org/). Writing a python-based indexer that runs on our infrastructure would be very straightforward. This work could also address, or go a long way toward addressing, #36. Or if typesense won't work, this issue entails getting search working... _somehow_. :wink:

**Comment by hinerm** [comment]
TODO:
- experiment with different stylings of the menu to add more spacing
- replace the top navigation links on the main page with the search bar

**Comment by ctrueden** [comment]
@hinerm As discussed, I'll work on the front page's top bar / navigation / hamburger, while you play with search bar styling tweaks.

**Comment by ctrueden** [comment]
With 7fd96b60f4d6669f4040e52d11f9bdf4d14acd77, the front page is tidied!
