### ISSUE TITLE
Restore width:100% table CSS

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej.github.io#130]
I suggest reverting https://github.com/imagej/imagej.github.io/commit/5c4103565140a6b23275656c97d759c613f57a91

All the tables I've seen look much better with `width: 100%` - especially when you have multiple tables that are now no longer aligned to each other:

![image](https://user-images.githubusercontent.com/1123809/120345442-16fb2800-c2c0-11eb-89f5-926bb69bf214.png)

**Comment by hinerm** [comment]
@ctrueden were there any pages that you explicitly thought looked better without `width: 100%`?

**Comment by ctrueden** [comment]
Yes, there were several. I will try to dig up links and post them here soon.

I think we are going to need a class that we can use as an option via something like `{.full-width}`.

**Comment by ctrueden** [comment]
OK, so I think it really depends on how wide your browser window is. For example, here is the table for "The menu bar" in `/learn` as a full-width, centered natural width, and left-aligned natural width table as rendered on my screen at full screen width:

![full-width-table](https://user-images.githubusercontent.com/556626/120902023-a0ce2c80-c603-11eb-8f24-910c4ee7f732.png)
![centered-table](https://user-images.githubusercontent.com/556626/120902021-a0359600-c603-11eb-88a1-0992067338e2.png)
![left-aligned-table](https://user-images.githubusercontent.com/556626/120902024-a166c300-c603-11eb-8165-4925925820dc.png)

I recall there being tables I thought were harder to read than this on my screen; I'll post a screenshot if I run across any. But even with the above, I think the full-width starts to create too much space between the two table columns, as the screen becomes very wide. But it's not terrible here, so maybe we should indeed make full-width the default again, and use CSS class overrides on tables where full-width is not ideal.
