### ISSUE TITLE
Figure out how to split up content (e.g. into extensions repository)

### ISSUE THREAD

**Issue by frauzufall** [imagej/imagej.github.io#14]
Because of the 1GB size limit we need a strategy for how to distribute content to not hit that limit. 

The current idea is to create an `extensions` repository where all the non core pages would live. We need to analyze how much that helps and how to distinguish core from extension pages.

**Comment by frauzufall** [comment]
Here is a first analysis of the mediawiki backup based on file extension (not super helpful though):
```bash
(base) ➜ find . -name '*' -type f -printf '%b.%f\0' | awk -F . -v RS='\0' '{if (NF==2) $(NF+1)=" "; s[$NF] += $1; n[$NF]++} END {for (e in s) printf "%15d %6d  %s\n", s[e]*512, n[e], e}' | sort -rn | numfmt --to=iec-i --suffix=B
         206MiB   1698  png
         105MiB    526  jpg
         104MiB     44  pdf
          94MiB     48  zip
          73MiB      8  mov
          68MiB     67  gif
          23MiB   4660  mw
          12MiB     46  PNG
         6,9MiB      7  swf
         2,2MiB      5  JPG
         760KiB     12  jpeg
         360KiB     16  svg
         4,0KiB      1  sh
```

**Comment by frauzufall** [comment]
After talking to @elevans, this is the status: 

The extension repository is something where resources for creating extensions (scripts, plugins, ...) are collected, as well as the documentation for existing extensions. This will be a new iteration of the currently available resources. We want to take the time to do it well. So we are hoping that we can for now keep everything in this repository, making it easier to get all the URLs working etc. and just restore something very similar to what people knew. If there is not enough space, we could outsource media files and link to it. We only know if that fits once we have the most recent mediawiki data.

**Comment by ctrueden** [comment]
So far, everything fits. I'm concerned that over time, the number of images being hosted in this repository will grow too big. But we'll cross that bridge when we come to it.
