### ISSUE TITLE
Plugin doesn't appear to exist in imageJ/FIJI

### ISSUE THREAD

**Issue by BrentonCavanagh** [imagej/imagej.github.io#141]
[plugins/colour-merge](https://imagej.github.io/plugins/colour-merge)  has minimal data & doesn't appear to exist in FIJI or ImageJ anymore according to the instructions on usage.

Do we flag pages like this as draft ?

**Comment by ctrueden** [comment]
@BrentonCavanagh It's part of the Cookbook update site.

What I'd like to do, to resolve this issue, is solve #97, restoring the ability to show a project icon up near the title of a page, which when moused over, explains what this page is relating to. Then we can attach the Cookbook icon to this page, and any other pages describing plugins that are part of that Cookbook update site.
