### ISSUE TITLE
biop-lookup-tables page

### ISSUE THREAD

**Issue by romainGuiet** [imagej/imagej.github.io#170]
Hi @team,

Some years ago I created [a page about some Lookup tables](https://imagej.github.io/plugins/biop-lookup-tables) (LUTs), [source](https://github.com/imagej/imagej.github.io/blob/main/_pages/plugins/biop-lookup-tables.md)

A-  during the migration some images followed and some others were lost (in the details section). Is there a way to retrieve them?

B- there was also a zip file containing the LUTs which is missing. The best is probably to remove it and just rely on the update site.

C- As these are just LUTs I'm not sure this page belongs to the plugin section.

Thank you again for the wonderful work! 

Best,

Romain

**Comment by alexcarisey** [comment]
Hi Romain,
Please check the new page and let me know if all the issues have been addressed. I have not changed the classification of your work though, I was thinking about adding the following tags: Color Processing / Montage / Visualization (Plugins is too general and no longer exists). What do you think?
Alex

**Comment by ctrueden** [comment]
@romainGuiet Thoughts?

**Comment by romainGuiet** [comment]
Looks awesome like this, sorry for the long delay of my reply!
Cheers,
R
