### ISSUE TITLE
Statbox (the “Vital statistics” sidebar) will dublicate team members if refreshed

### ISSUE THREAD

**Issue by velissarious** [imagej/imagej.github.io#171]
How to replicate the bug:

1. Open a page with a statbox for example: https://imagej.github.io/plugins/bdv/
2. Expand "Team" on the statbox.
3. Click on the refresh icon of the statbox.
4. The names of the team members will be duplicated. 🐛 

Here are three pictures, before clicking the refresh icon and after one click and a second click.
![image](https://user-images.githubusercontent.com/23398764/122018651-59922980-cdc3-11eb-8933-1f289d22b8c3.png)
![image](https://user-images.githubusercontent.com/23398764/122018706-66af1880-cdc3-11eb-9318-36f0b34b9bbb.png)
![image](https://user-images.githubusercontent.com/23398764/122018792-79295200-cdc3-11eb-9569-773c2271203a.png)

It appears that each time the refresh button is clicked the team members will be duplicated, it happens every time with no apparent limit.

**Comment by ctrueden** [comment]
Thanks for the report, @velissarious! However, there is already an issue for this: #110.
