### ISSUE TITLE
Error in user page front matter: `hoerldavid`, `krzysg`

### ISSUE THREAD

**Issue by mattxwang** [imagej/imagej.github.io#172]
I was looking to do some other ticket work, and there are two errors regarding user page generation:

```
Error: YAML Exception reading /Users/matt/code/imagej.github.io/_pages/people/hoerldavid.md: (<unknown>): did not find expected '-' indicator while parsing a block collection at line 2 column 1
Error: YAML Exception reading /Users/matt/code/imagej.github.io/_pages/people/krzysg.md: (<unknown>): did not find expected '-' indicator while parsing a block collection at line 2 column 1
```

Going from `main`, the two issues are list blocks that likely should be key-value front-matter;

```yaml
# hoerldavid.md
---
- User:Davidhoerl
- User:Hoerldavid
title: David Hörl
...
```

```yaml
# krzysg.md
---
- User:Gonciarz
- User:Krzysztof.Gonciarz
title: Krzysztof Gonciarz
...
```

This might've been spillover from https://github.com/imagej/imagej.github.io/commit/1b7f8c32add0ae80d990819c73d698ff83c2be37 ?

Not exactly sure what the best way is to proceed here (I don't want to delete other people's page content!), @ctrueden any thoughts?

**Comment by ctrueden** [comment]
Thanks @mattxwang, indeed, those list items should have been removed when I removed the `mediawiki:` keys. Fixed now.
