### ISSUE TITLE
Problem downloading the OlympusImageJplugin

### ISSUE THREAD

**Issue by YinHana0505** [imagej/imagej.github.io#187]
Hi, 

I was on this page https://imagej.net/formats/olympus to download the plug in to view Olympus microscopy images. But when i click download, nothing happened and I have tried multiple times. Its like the zip file does not exists. Can someone clarify what is the issue with this? How else would I be able to install olymplus plug in to ImageJ?

**Comment by ctrueden** [comment]
@YinHana0505 I just tried, and it works for me now. Anyway, this is an external link to the Olympus website. We cannot fix it on our side, except to mirror the binaries. We could consider doing that if the Olympus site keeps going down, but I'd rather not if we don't have to. Could you give it another try and see if you can get the file(s) now?

**Comment by YinHana0505** [comment]
Hi,

I have just tried again but it doesn't work. Just to clarify I was attempting to download the file by clicking "here" in the screenshot below, but nothing is loaded. Could I ask how do you obtain the zip file?  Is it possible for you to send me the zip file directly?

Thanks alot

![image](https://user-images.githubusercontent.com/85520531/123268972-1c4f3980-d531-11eb-99bd-2798eb7f1863.png)
