### ISSUE TITLE
link broken at distance analysis page

### ISSUE THREAD

**Issue by brinads** [imagej/imagej.github.io#189]
the hotlinks on the following text  (located at https://imagej.net/plugins/distance-analysis) lead to non-existent pages:

- Spot segmentation method : a tutorial for this method is found here

- Iterative segmentation method : a tutorial for this method is found here

**Comment by ctrueden** [comment]
I believe @mcib3d fixed this earlier today with 67b068627946dca9d65d67a777bef12714215838.
