### ISSUE TITLE
Conversion: Handle Conference pages

### ISSUE THREAD

**Issue by frauzufall** [imagej/imagej.github.io#19]
We probably need a layout for pages like `Conference-2006.mw`:
```
{{Conference
| title=ImageJ 2006 User & Developer Conference
| section=1st ImageJ User & Developer Conference
| dates=18 - 19 May 2006
| image=Imagej-conference-2006.jpg
| location=CRP Henri Tudor in Luxembourg
| link=http://imagejconf.tudor.lu/archive/imagej-user-and-developer-conference-2006
}}
```
Nothing of the content of the file is currently rendered on the generated page.

**Comment by elevans** [comment]
This is now implemented.

Original Example:
[Web archive](https://web.archive.org/web/20171021073737/http://imagej.net/Conference_2012)

New Example:
[GitHub pages](http://imagej.github.io/pages/demo-conference)
