### ISSUE TITLE
Add redirects

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej.github.io#2]
We should add redirects for `imagej.github.io`: 
* `use.imagej.net`
* `user.imagej.net`
* `imagej.net`
* `imagej.net/Use`

and for `imagej.github.io/develop.html`:
* `develop.imagej.net`
* `developer.imagej.net`
* `devel.imagej.net`
* `imagej.net/Develop`

**Comment by ctrueden** [comment]
Why not `imagej.net` toplevel goes to `imagej.github.io`?

**Comment by hinerm** [comment]
sounds good

**Comment by hinerm** [comment]
how about `imagej.net/Use` and `imagej.net/Develop`..

**Comment by ctrueden** [comment]
I think the "user" page should be _the_ default ImageJ page. Because that is 90+% of our target audience.

**Comment by hinerm** [comment]
yeah I meant "in addition to"

**Comment by ctrueden** [comment]
We decided to have a single [Welcome](http://imagej.net/Welcome) page, and keep it on the wiki so that people can edit it more easily, and so that it is integrated with the rest of the web site.
