### ISSUE TITLE
Conversion: Galleries

### ISSUE THREAD

**Issue by frauzufall** [imagej/imagej.github.io#21]
This is a mediawiki gallery which should get special attention during conversion:
```
<gallery>
File:hackathon-2016-konstanz-hackers.jpg|caption|Hackers!
File:hackathon-2016-konstanz-dinner.jpg|caption|Hackers at dinner
File:hackathon-2016-konstanz-rueden.jpg|caption|{{Person|Rueden}}
File:hackathon-2016-konstanz-harrington.jpg|caption|{{Person|Kharrington}}
File:hackathon-2016-konstanz-domander.jpg|caption|{{Person|Rdom}}
File:hackathon-2016-konstanz-hoerl.jpg|caption|{{Person|hoerldavid}}
File:hackathon-2016-konstanz-dietz-and-rueden.jpg|caption|{{Person|Dietzc}} and {{Person|Rueden}}
File:hackathon-2016-konstanz-harrington-and-gunther.jpg|caption|{{Person|Kharrington}} and {{Person|skalarproduktraum}}
File:hackathon-2016-konstanz-helfrich-and-pietzsch.jpg|caption|{{Person|Stelfrich}} and {{Person|Pietzsch}}
File:2016-hackathon-konstanz-sushi.jpg|caption|KNIME 3.2: sushi edition
File:hackathon-2016-konstanz-amazing-salt.jpg|caption|The gravity-defying salt shaker!
</gallery>
```
Example file:  `2016-07-21_-_KNIME_Image_Processing_hackathon.mw`

**Comment by elevans** [comment]
This is what that page looks like:
https://web.archive.org/web/20170613211035/http://imagej.net/2016-07-21_-_KNIME_Image_Processing_hackathon

There is something kind of like that `image-row` that I worked in. Its really really clunky and I hate it. Its a terrible hack that uses markdown tables to render an images in a grid with text. The `figure-left` and `figure-right` includes uses the same trick but is much nicer and is clean to work with. Maybe we can use that existing CSS styling and render something closer to this? My major issue is how would the author interact with this? I think if she had to do something like `{% include gallery image1=path image1=text image2=path image2=text %}` it would become easily confusing.

Thoughts?

**Comment by frauzufall** [comment]
@elevans can we use a table with `src | description` columns in a `gallery` include, same way you did for the `menu` includes? Together with the script I added for making thumbnails clickable (`thumbnail` include) this could work.

**Comment by elevans** [comment]
@frauzufall Interesting idea! I like it. Let me give it a shot. I'll report back with what I got.

**Comment by elevans** [comment]
@frauzufall I've implemented the gallery.

Examples:
[old gallery](https://imagej.net/2016-07-21_-_KNIME_Image_Processing_hackathon)
[new gallery](http://imagej.github.io/demo-gallery).

I haven't tried it yet, but I think it should also still work with `thumbnail`.
