### ISSUE TITLE
Bring back menus

### ISSUE THREAD

**Issue by frauzufall** [imagej/imagej.github.io#23]
The side menus were handled by templates and we need them back, they are currently printed as e.g. `%Replace% AboutMenu %Replace%` and their content needs to be restored from the wikimedia templates.

**Comment by elevans** [comment]
Looks like its a variation of the infobox (now details-box). I'll get this added in.

**Comment by elevans** [comment]
I've implemented the `AboutMenu`.

Original example:
[Web archive example](https://web.archive.org/web/20190930025617/https://imagej.net/ImageJ)

New example:
[GitHub pages example](https://imagej.github.io/pages/demo-about-menu)

The usage is the same.

**Comment by frauzufall** [comment]
Nice! 

There are many other menus missing though. Dummy includes already exist. Maybe they should use a common `menu` include so that not every menu needs to implement the whole html structure of the menu in there, but rather has a bunch of `menuitem` includes, similar to the original menu templates.

**Comment by elevans** [comment]
Ahh I see. Let me take a look at them all together. I think you're right, we'll just have a common menu if that makes sense.

**Comment by ctrueden** [comment]
A single `menu` include would be amazing, if you can pull it off. That is what I tried to do with the MW templates: there is a template for each specific menu, that then calls the generic menu template(s), so we stay as [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) as possible.

What I don't think you want to do is have a single `menu` template, and then on every page that is part of a "set", copy/paste that set's menu structure using a direct include of the `menu`. I think we should do it like the MW site did it: with a [two-level effect](https://www.youtube.com/watch?v=RZvsGdJP3ng). :smile:

**Comment by elevans** [comment]
I've played around a little bit with a generic Menu. I think its totally doable. Not sure if I can do nested `includes` but I suspect that will be just fine. I'm probably using some nested `includes` somewhere already.

**Comment by elevans** [comment]
@ctrueden @frauzufall Okay I think I've brought back the menu system. Check out the [Git Menu](http://imagej.github.io/pages/demo-git-menu) and the source for it. Now if you want to make a new menu all you need to do is create a new `include` and include `menu` , give it a title and in the `content` field input a markdown table with links.

Thats it! How's that?
