### ISSUE TITLE
OlympusImageJPlugin download link incorrect

### ISSUE THREAD

**Issue by shuffle2** [imagej/imagej.github.io#246]
the file is available at https://www.olympus-lifescience.com/data/File/OlympusViewer-win.zip 
`OlympusViewer-mac.dmg` is available in the same directory.

The existing links do not work.

**Comment by imagejan** [comment]
I tried just now and found the existing links http://www.olympus-lifescience.com/OlympusImageJPlugin/OlympusViewer_Win and http://www.olympus-lifescience.com/OlympusImageJPlugin/OlympusViewer_Mac working fine.

(Source code at the time of this writing: https://github.com/imagej/imagej.github.io/blob/e9567320326e4da782e37380e5ae9098e5720a4c/_pages/formats/olympus.md)

Maybe it was a temporary issue? I'm going to close this, but please feel free to re-open with more details if the issue persists on your side.
