### ISSUE TITLE
Support oneboxed links

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej.github.io#27]
Discourse reads Open Graph and oEmbed metadata from pages to generate oneboxed links. To support that, I _believe_ all we need to do is add some `meta` tags to our page layout [here](https://github.com/imagej/imagej.github.io/blob/158be6ff9830dc61287d20df06f3a90eba8f16ab/_layouts/page.html#L3-L11). See [this gist](https://gist.github.com/davidensinger/5431869) for an example.

**Comment by imagejan** [comment]
See [this forum topic](https://forum.image.sc/t/opengraphmeta-mediawiki-extension/4630?u=imagejan) for the two mediawiki extensions that were involved.

In particular, it's these four `<meta>` tags as exemplified on the [BigStitcher](https://imagej.net/BigStitcher) page:

```
<meta property="og:type" content="article"/>

<meta property="og:site_name" content="ImageJ"/>

<meta property="og:title" content="BigStitcher"/>

<meta property="og:description" content="The BigStitcher is a software package that allows simple and efficient alignment of multi-tile and multi-angle image datasets, for example acquired by lightsheet, widefield or confocal microscopes. The software supports images of almost arbitrary size ranging from very small images up to volumes in the range of many terabytes, which are for example produced when acquiring cleared tissue samples with lightsheet microscopy."/>
```
