### ISSUE TITLE
Duplicate Wiki pages

### ISSUE THREAD

**Issue by junelsolis** [imagej/imagej.github.io#275]
There are duplicate wiki pages for the ColonyArea plugin:
https://imagej.net/plugins/colony-area
https://imagej.net/plugins/colonyarea

@ctrueden is it okay for me to go ahead and merge the information in these two duplicate pages into a single file?

**Comment by ctrueden** [comment]
@junelsolis Ahh, thanks for noticing that. I didn't realize when I merged your PR #274. Yes, would be great if you can combine them. :+1:

**Comment by junelsolis** [comment]
Commit a43b3cdf0d23e7f68bab088d1db521267c5222c4 combines the content from the duplicate files. Content now resides in the original [colonyarea.md](https://github.com/imagej/imagej.github.io/blob/main/_pages/plugins/colonyarea.md).

Thanks @ctrueden for the quick response.
