### ISSUE TITLE
Example code missing on  imagej.github.io

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/imagej.github.io#28]
Hi all,

I just discovered an important difference between the new website on imagej.github.io and imagej.net: Example code is missing as shown here:

![image](https://user-images.githubusercontent.com/12660498/89767255-da282f80-daf9-11ea-847d-41808276848f.png)

And here are the links to the two pages:

http://imagej.github.io/ImgLib2_Examples

https://imagej.net/ImgLib2_Examples

Thanks everyone involved for working on this btw. the new website is a big step forward!

Cheers,
Robert

**Comment by ctrueden** [comment]
@haesleinhuepf Thanks for the report!

As far as troubleshooting problems like this: first we want to find out whether information was actually lost in the conversion.

* [New Markdown source](https://github.com/imagej/imagej.github.io/blob/01472f90ca245b3759c0c450ddc07aa6a1dce654/_pages/ImgLib2_Examples.md) (as of this writing) 
* [MediaWiki source](https://github.com/imagej/imagej.github.io/blob/mediawiki-final/ImgLib2_Examples.mw) (from `mediawiki-final` tag)

The MediaWiki code embedding the code for Example 1c is:
```mediawiki
{{GitHubEmbed|org=imglib|repo=imglib-tutorials|source=Example1c.java}}
```

And in the Markdown we see:
```liquid
{% include github-embed org='imglib ' repo='imglib-tutorials ' source='Example1c.java ' %}
```

So good news: we didn't actually mangle anything in the conversion. We just need to complete the Liquid `include` that embeds content from GitHub. We'll have to research the best way to do this in a way compatible with GitHub Pages. I'm guessing it will require some JavaScript.

**Comment by imagejan** [comment]
I don't know if this is relevant here, but for `gist`s there's this one:
https://github.com/jekyll/jekyll-gist

**Comment by ctrueden** [comment]
I'm going to use https://emgithub.com/ for this.
