### ISSUE TITLE
REST API search functionality (JSON)

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej.github.io#36]
Is there some way to get search results in JSON format already, e.g. via a REST API?
If not, maybe this can be added e.g. using https://github.com/riichard/jekyll-rest-api

(Related to #13.)

This would allow updating the built-in `imagej.net` search in `scijava-search`, see https://github.com/scijava/scijava-search/pull/20.

**Comment by ctrueden** [comment]
As of f88e8fc94de8a71ffb83ac790f2ecec8f1c105f2, we are now using [typesense](https://typesense.org) on search.imagej.net at port 8108 over HTTPS. It has a [REST API for doing searches](https://typesense.org/docs/0.19.0/api/documents.html#search).
