### ISSUE TITLE
Fix deprecated MathJax usage

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej.github.io#43]
Browser says:
```
WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
```

**Comment by ctrueden** [comment]
@elevans We _are_ using that retired subdomain:
```
$ git grep cdn.mathjax
_includes/base-scripts:<script type="text/javascript" async src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML"></script>
```
Would it be sufficient to change the `_includes/base-scripts` accordingly?

**Comment by elevans** [comment]
@ctrueden I see what happened here. The MathJax script include I was working with is `_includes/mathjax-scripts`. I guess at some point the old retired subdomain made it into `_includes/base-scripts` and is being flagged correctly by the browser. Removing the old subdomain from `base-scripts`resolves the warning. I don't think it makes sense to keep the MathJax scripts separate. I'll merge it into `base-scripts` and call it a day.
