### ISSUE TITLE
about/usage URL is out-of-date

### ISSUE THREAD

**Issue by smgriffin2** [imagej/imagej.github.io#49]
The url on the usage page leads to a page that no longer exists:

https://juglab.mpi-cbg.de/matomo/

**Comment by ctrueden** [comment]
Yep. I've been in communication with the CSBD/MPI-CBG team about it, but no one there has the bandwidth to restore the Matomo instance. The main person who has advocated for ImageJ/Fiji usage maps in the past is @tomancak; if it's important to him, we can discuss a way forward to restoring that functionality somehow.

**Comment by ctrueden** [comment]
I deleted the usage page, in favor of 301 redirects to https://usage.imagej.net/

I've been working on setting up analytics on that subdomain, but it's not ready for public consumption yet, and won't be before we launch the wiki next Friday.

So for the moment: no publicly viewable statistics!
