### ISSUE TITLE
Sort all pages into concise subdirs, and use standard-web-naming

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej.github.io#51]
All pages should be classified into subdirs. As of this writing, there are a few pages still with the MediaWikiNaming directly in the `_pages` folder. We need to classify these.

And finalize where things currently live. Some existing structure is questionable, including:

* `tutorials/*` vs `scripting/examples/*` scripts (needs unification)
* `/update-sites` should move to `/help` or `/learn` to avoid confusion with `/sites` (which is a section for pages about each update site people care to document on the wiki)

**Comment by ctrueden** [comment]
At today's status meeting we agreed to similarly classify the `/media` folder, using a folder structure shadowing the one in `_pages`—when the resources in question correspond to a particular page or group of pages.

**Comment by hinerm** [comment]
* move SciJava to `/libs` and merge with `/libs/scijava-common`

**Comment by ctrueden** [comment]
This issue is now almost completely resolved:
* All top-level pages have been filed.
* `scripting/examples` was unified into `tutorials`.

All that remains is to reconcile `/update-sites` and `/sites` somehow.
