### ISSUE TITLE
Convert mediawiki namespace links

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej.github.io#55]
MediaWiki category-style links no longer work. Each link needs to be replaced with a link to the appropriate equivalent page, e.g. `[:Category:plugins]` --> https://imagej.github.io/plugin_grid (or similar)

Known namespaces:
- [x]  `[:Category:...]`
- [x] `[File:...]`
- [x] `[Special:...]`
- [x]  `User:`
- [x] `Template:`

**Comment by Adityachaturvedi2906** [comment]
Hey! this issue seems interesting, can I work on this? Please guide me further on the same

**Comment by Adityachaturvedi2906** [comment]
> 
> 
> @Adityachaturvedi2906 What is your motivation for helping? Are you familiar with MediaWiki? Are you familiar with GitHub Pages? Are you familiar with the ImageJ community, and/or the scientific imaging community in general?

Thank you for your response, my motivation for helping is to contribute to this community and see my piece of code using in the real-world few days ago I submitted a proposal for GSoC'21 and I choose Wikimedia so from there I came to know about Mediawiki and I am really looking forward to contributing and help in this organisation even after the GSoC period although I am not familiar with ImageJ community surely I'll get through it.

Can you please guide me further?

Thanks
Aditya chaturvedi

**Comment by Adityachaturvedi2906** [comment]
> 
> 
> @Adityachaturvedi2906 It looks like @hinerm took care of this one. We're in the middle of an active sprint on this project, so things are shifting rapidly. If there is anything else you'd like to try working on, let us know. But note that this project is _not_ based on MediaWiki, but rather a migration _away_ from it to Jekyll.

I would love to work on something great with you all, I am only looking for new opportunities to improve my skills and share what I learn.
