### ISSUE TITLE
Make the news page work again

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej.github.io#61]
News page needs to liquid loop over all news articles, and show them in a grid like before. And consider showing blurbs for the last couple of articles with "read more" or some such.

**Comment by hinerm** [comment]
All news pages need to be [slugified](https://jekyllrb.com/docs/liquid/filters/):
* underscores -> dashes
* downcase all
* remove non-alphanumerics

Add twitter sidebar?

**Comment by hinerm** [comment]
Reminder: starting point with `where`
```
{%- assign news-pages = site.pages | where_exp:"site",
"site.url startswith '/news/'" -%}

{%- assign news-pages = site.pages | where_exp:"site",
"site.url contains '/news/'" -%}
```

**Comment by hinerm** [comment]
Completed in:
968e5c372d30a1e19ad19ece039bd5d4ea699b4f
https://github.com/imagej/imagej.github.io/commit/cda15aa71b87a20b3998f035fa8d8540781743ea
https://github.com/imagej/imagej.github.io/commit/d15960c724084680b779dee52a424a4b3dcb8424
https://github.com/imagej/imagej.github.io/commit/d6cfc5f072046ec043c8945fd2fce8d4205ba33d
