### ISSUE TITLE
Use specific names for include parameters

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej.github.io#69]
In templates we should avoid `content = ...` use. We should be able to specify a more specific element

**Comment by ctrueden** [comment]
This work was mostly completed. The following includes still use a `content` parameter:

| Include | Comments |
|-----|-----|
| aside | Appropriate |
| clear | Slated for removal; see #114 |
| gallery | Slated for cleanup; see #154 |
| info-box | Slated for removal; see #59 |
| notice | Appropriate |
| project | Slated for removal; see #97 |
