### ISSUE TITLE
Finalize the git history

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej.github.io#7]
We want the git history of the main branch to reflect the entire history of the ImageJ wiki from its MediaWiki days (same as we've done with https://github.com/openspim/openspim.github.io/). It's doable with git-remote-mediawiki backend. Concerns to watch out for:

* The main branch history will break when we force push, but we're still in the initial development phase right now, so that's OK. Any interested folks who've cloned it can force reset.
* The conversion of authors from MediaWiki names to real names + emails needs to be handled.
* Large binaries need to be excluded from the history.
* We want to split out the extensions (e.g. plugins) to their own repository, so we may need to be more clever and split the big MediaWiki history into two histories: one for extensions pages, and one for core pages. This will be more involved.

**Comment by frauzufall** [comment]
Is this done?

**Comment by ctrueden** [comment]
Yes! Thanks for circling back.
