### ISSUE TITLE
Default icons for all pages

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej.github.io#89]
The search bar shows an icon for each page. But most pages don't have custom icons. We should unify this infrastructure with that of the plugin index, so they both use the same icons, and establish default icons for pages in all categories and/or site sections. Need to decide on reasonable conventions for this, and add the icons accordingly. No broken images!

**Comment by hinerm** [comment]
@ctrueden adding an icon to each page means [every page gets a statbox](https://github.com/imagej/imagej.github.io/blob/820d8eb0927be2c9a58de3da76cda272566fadd5/_includes/statbox#L207-L211). Do you want to work around that as part of https://github.com/imagej/imagej.github.io/issues/59?

**Comment by hinerm** [comment]
See c104bd5bcb306a266583db5521147509d368f471

**Comment by ctrueden** [comment]
@hinerm Good point... let's just remove the `or image` part of that conditional? If the only piece of statbox-related metadata is an icon, then populating the statbox seem worthwhile to me.
