### ISSUE TITLE
Make the font size more consistently palatable

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej.github.io#94]
@frauzufall wrote:
> I am using the site comfortably with 120% scale, the font is way too small for me by default

But on my screen it looks really good, maybe even too large. Probably we need to switch to percentage scale for the base font, and `rem` units for all other font adjustments; see [this article](https://betterwebtype.com/articles/2019/06/16/5-keys-to-accessible-web-typography/) for details.

**Comment by hinerm** [comment]
It's uncomfortably small for me, too. Windows, 3840x2160 + 250% scale. Chrome is worse than firefox.

**Comment by ctrueden** [comment]
@frauzufall @hinerm Is the font on the old site also small for you? Here is a comparison of the two sites on my Ubuntu 20.04 machine with Firefox. As you can see, for me, there isn't too much difference. Is it a big change for you?

![old-site-font](https://user-images.githubusercontent.com/556626/117099499-f2e70e00-ad36-11eb-99f7-58e030b525f8.png)
![new-site-font](https://user-images.githubusercontent.com/556626/117099506-f67a9500-ad36-11eb-9d8b-f8bc3c5a6074.png)

It looks like the body `font-size` is set to `1.125em` on the old site, and set to `11pt` on the new one. Could you try changing `assets/css/main.css` from `11pt` to `1em` and see how that looks for you? It seems OK for me, although we'll probably need to tune some other fonts in response to that change.

**Comment by hinerm** [comment]
@ctrueden the old site has fine readability to me.

This is what the sites look like side-by-side (chrome) for me:
<img src="https://user-images.githubusercontent.com/1123809/117164982-b80ec580-ad8a-11eb-8ad1-b984a9a7c1c5.png" width="300">

The new font is also narrower and lighter, and I think that lack of contrast further reduces readability. Firefox renders the font slightly darker and is a bit more readable.

>Could you try changing assets/css/main.css from 11pt to 1em and see how that looks for you?

`1em` is an improvement over `11pt` for me.

**Comment by ctrueden** [comment]
@hinerm Please close if it looks good. Or if not, please change from `90%` to whatever is needed (`95%`? `100%`?) to make it look good on your system.
