### ISSUE TITLE
Rename all media files to be web-lower-case

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej.github.io#98]
The [TrackMate](https://imagej.github.io/plugins/trackmate/index) page is a good example of many image links with mixed case. These are not found because the links have had the first word downcased.

If the site is built with Jekyll 4.2, the images show as expected.

Options:
1. Fix links to be case-appropriate
1. Rename media to be web-down-case and update links
1. Build via GitHub actions

**Comment by hinerm** [comment]
@ctrueden am I missing some kind of obvious workaround here?

**Comment by hinerm** [comment]
>Make sure you get the case right:

Ahhhh yeah ok.. it looks like media links to images all got the first word downcased, but the filenames weren't renamed (e.g. [TrakEM2](https://imagej.github.io/plugins/trakem2/index) has all its images broken too). Jekyll 4.2 must be doing some case insensitivity. Renaming the issue accordingly

**Comment by ctrueden** [comment]
> it looks like media links to images all got the first word downcased, but the filenames weren't renamed

It's because MediaWiki always _upcases_ all pages and file entities, even if the link is written downcased in the MediaWiki markup. So nothing got mangled in the conversion—we just aren't doing our own mangling anymore. :wink:

**Comment by hinerm** [comment]
>Unfortunately, that also means a bunch more stuff added to redirects.txt

@ctrueden I was just thinking - do we actually have to add web-down-case-ification to `redirects.txt`? Should we consider a blanket web-down-case-ify rule that would just redirect any old links automatically to the new pages?

**Comment by ctrueden** [comment]
> Should we consider a blanket web-down-case-ify rule that would just redirect any old links

Hmm, that's a good idea. I wasn't thinking `mod_rewrite` would be powerful enough to do that, but apparently it might be:

```apache
# https://stackoverflow.com/a/2924084/1207769
RewriteMap lc int:tolower
RewriteRule ^/(media/.*)$ /${lc:$1} [R=301]
# https://stackoverflow.com/a/1279758/1207769
RewriteRule       ^(/media/.*/[^/]*?)_([^/]*?_[^/]*)$ $1-$2 [N]
RewriteRule       ^(/media/.*/[^/]*?)_([^/_]*)$       $1-$2 [R=301]
```

Not pretty, but it could work. We'll also want to replace spaces with dashes, and squeeze out some other non-alphameric characters, though.

**Comment by hinerm** [comment]
See also #29
